# Generated by Django 5.1.2 on 2024-10-27 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": (["-publish"],)},
        ),
    ]
